spring:
  batch:
    job:
      # job??? ???? ? Job??? ?? job? ??????.
      # ex) java -jar batch.jar --job.name=expirePointJob
      # ? ??? ???? spring.batch.job.names? job.name?? ???? ?? ? ?? ???.
      # ??? Job ??? ?? ??? ?? Job? ?????.
      # ??? ???? ?? Job??? NONE?? ????? job??? ?? ??? ?? ??? Job? ????? ????.
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always # batch?? ???? ??? ????? always? ??
  jpa:
    show-sql: true # JPA? ??? SQL? ?????.
    hibernate:
      ddl-auto: validate # entity? ?? ???? ?????? ?? ??? validate (??? ??? ???)? ??
  datasource: # datasource ??
#    url: jdbc:mysql://127.0.0.1:33060/point?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver # ???? ????? mysql? ??
    username: root
    password: 1q2w3e4r